console.log('Hello, Node js..');
console.log('Testing from "main.."');
console.log('Added wording...');
console.log('Set to staging...');
console.log('Removed env variables..');
console.log('package.json ignored..');
console.log('dev-branch added..');
console.log('set default..');
console.log('grep version..');
console.log('checking key words!!');
console.log('checking published!!');
console.log('Type to types..!!');
