# This is a basic workflow to help you get started with Actions

name: Main Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-node:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #environment: main
    container: node:16

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      - run: node --version
      - run: npm --version
      

      - run: npm install
      - run: node app.js
