
Skip to content
Pull requests
Issues
Marketplace
Explore
@NowsGT
NowsGT /
Node-js-Demo
Public

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights

    Settings

Node-js-Demo/.github/worklfows/main_deploy.yml
@NowsGT
NowsGT Created main_deploy.yml
Latest commit cc3bba2 3 minutes ago
History
1 contributor
31 lines (26 sloc) 897 Bytes
# This is a basic workflow to help you get started with Actions

name: Main Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-node:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: main
    container: node:16

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: node app.js
Footer
© 2022 GitHub, Inc.
Footer navigation

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

Node-js-Demo/main_deploy.yml at main · NowsGT/Node-js-Demo
