# This is a basic workflow to help you get started with Actions

name: On_push_tag Deploy

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-node:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development
    #container: node:16

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: 'cat package.json'
        run: cat ./package.json | grep "version"
