# This is a basic workflow to help you get started with Actions

name: Release Test

# Controls when the workflow will run      
on:
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prerelease-staging:
    uses: ./.github/workflows/test_deploy1.yml
    with:
     token: ${{ secrets.ACCESS_TOKEN }}
     
  release-production:
    if: 'github.event.release.prerelease'
    uses: ./.github/workflows/test_deploy2.yml
