# This is a basic workflow to help you get started with Actions

name: Test Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - '.version'
      - 'VERSION'
      - '.github/**'
      - '.aws/**'
      - '.scripts/**'
      - 'package.json'
      - 'dist/web-lib/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-merge:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: npm install

      - run: echo "cp src/config/env.example.js src/config/env.js"

  auto-bump:
    runs-on: ubuntu-latest
    environment: development
    needs: [ check-merge ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: npm install

      - run: echo "cp src/config/env.example.js src/config/env.js"

      - name: Auto-Bump & Tag
        run: echo ".scripts/build_tag.sh"
  trigger-deploy:
    runs-on: ubuntu-latest
    environment: development
    needs: [ check-merge, auto-bump ]
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: npm install
      - name: Configure AWS Credentials
        run: echo "end of the script.."

  build:
    runs-on: ubuntu-latest
    environment: development
    needs: [ trigger-deploy ]
    steps:
      - uses: actions/checkout@v2
      # Set APT_VERSION
      - run: export APT_VERSION=`cat VERSION`
      - run: IFS="." read -r V_MAJOR V_MINOR V_PATCH <<< $APT_VERSION
      - run: rm -f ./src/config/env.js 
      # start
      # install the RNAPP dependencies
      - name: echo Installing dependencies...
        # Setup env.js file
        env:
          APT_ENV_JS: ${{ secrets.APT_ENV_JS }}
        run: echo "$APT_ENV_JS" >> ./src/config/env.js
      - run: yarn install
      # install rn cli for building bundles
      - run: npm i -g react-native-cli
      # build the RNAPP
      - run: yarn run web:production
      # build the rn-app BUNDLES
      - run: npm i
      - run: mkdir ~/bundle-output
      - run: react-native bundle --entry-file ./index.ios.js --dev false --platform ios --bundle-output ~/bundle-output/main.ios.jsbundle
      - run: react-native bundle --entry-file ./index.android.js --dev false --platform android --bundle-output ~/bundle-output/index.android.bundle


