# This is a basic workflow to help you get started with Actions

name: Release Test

# Controls when the workflow will run      
on:
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  prerelease-staging:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run Workflow on Staging
#        uses: actions/workflow-dispatch@v2
#        with:
#          workflow: test_deploy1.yml
#          token: ${{ secrets.APT_DEPLOYMENT_ACCESS_TOKEN }}
#
#  release-production:
#    if: 'github.event.release.prerelease'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run Workflow on Production
#        uses: actions/workflow-dispatch@v2
#        with:
#          workflow: test_deploy2.yml
#          token: ${{ secrets.APT_DEPLOYMENT_ACCESS_TOKEN }}

jobs:
  prerelease-staging:
    - name: Run Workflow on Staging
      uses: ./.github/workflows/test_deploy1.yml
      with:
        token: ${{ secrets.APT_DEPLOYMENT_ACCESS_TOKEN }}

  release-production:
    if: 'github.event.release.prerelease'
    uses: ./.github/workflows/test_deploy2.yml
