# This is a basic workflow to help you get started with Actions

name: Release Test

# Controls when the workflow will run      
on:
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prerelease-staging:
    name: Run Workflow on staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         token: ${{ secrets.ACCESS_TOKEN }}

      - name: Run Test Deploy 1
        uses: ./.github/workflows/test_deploy1.yml
     
  release-production:
    if: 'github.event.release.prerelease'
    name: Run Workflow on Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Test Deploy 1
        uses: ./.github/workflows/test_deploy2.yml
